### ISSUE TITLE
[Request] Add 0x V3 & V4

### ISSUE THREAD

**Issue by akshatmittal** [ProjectOpenSea/marketplace-benchmarks#29]
Basically title. Since 0x is the largest open marketplace protocol which specifically boasts about gas savings, it would be great to add it to this benchmark.

0x V3 is fully generalized like Seaport.
0x V4 currently implements limited NFT features, with full generalized capabilities said to be "coming soon"

**Comment by arr00** [comment]
Agree! We are requesting that all marketplace creators add their marketplace for benchmarking. Hopefully 0x will add theirs soon.
